version: '3'

services:
  parser:
    build: ./parser
    depends_on:
      - db

  bot:
    build: ./bot
    depends_on:
      - db

  db:
    restart: always
    build: ./db
    image:
      postgres:16.1
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "il_patio_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"