version: '3'

services:
  parser:
    build: ./parser
    depends_on:
      - database
    networks:
      - skibidi
  
  bot:
    build: ./bot
    depends_on:
      - database
    networks:
      - skibidi

  database:
    restart: always
    image:
      postgres:latest
    expose:
      - 5432
    ports:
      - "5432:5432"
      - "5433:5433"
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_DB: "il_patio_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
      - ./database/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - ./database/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    networks:
      - skibidi

volumes:
  postgres-data:
    driver: local

networks:
  skibidi: